### PR TITLE
Add metadata

### LINKED ISSUE #82: Optional `metadata` type
Sometimes, converting `input` to `output` requires some additional metadata. E.g. there is a select in UI with a list of items, each item is of `Foo.t` type which is a record `{id: int, label: string}`. Select's value is stringified `id`. In the output, there should be `Foo.t`. To get the output value in validator, `array(Foo.t)` is required.

It's achievable in the current state of things by:
- storing in `input` `Foo.t` instead of stringified id
- storing in input all `foos: array(Foo.t)` so it's available in validator

But neither looks nice to me.

Proposal: introduce an optional `metadata` type. If defined, it would be passed as a second argument to validators.

```reason
module Foo = {
  type t = {
    id: int,
    label: string,
  };
};

module Form = [%form
  type input = {foo: string};
  type output = {foo: Foo.t};
  type metadata = {foos: array(Foo.t)};
  let validators = {
    foo: {
      strategy: OnFirstChange,
      validate: (input, metadata) =>
        switch (
          metadata.foos
          ->Array.getBy(foo =>
              input.foo
              ->Int.fromString
              ->Option.mapWithDefault(false, id => id == foo.id)
            )
        ) {
        | Some(foo) => Ok(foo)
        | None => Error("Invalid foo")
        },
    },
  }
];

[@react.component]
let make = (~foos: array(Foo.t)) => {
  let form = Form.useForm(
    ~initialInput={foo: ""},
    ~metadata={foos: foos},
    ~onSubmit={...}
  );
  ...
};
```

### PR DESCRIPTION
**Pull request by alexfedoseev**
Closes #82 #94

### CODE REVIEW

**Comment by alexfedoseev** [comment]
@johnhaley81 @dan003400 Would you mind to try out `re-formality@4.0.0-beta.10`?

**Comment by dan003400** [comment]
> @johnhaley81 @dan003400 Would you mind to try out `re-formality@4.0.0-beta.10`?

Do you have an example of the new API for meta data?

**Comment by alexfedoseev** [comment]
It's here: https://github.com/MinimaHQ/re-formality/blob/metadata/examples/src/BlogPostForm.re#L8

**Comment by dan003400** [comment]
I'll work on migrating our forms over this week and let you know how it goes.

**Pull request merged**
